import type { NextPage } from 'next';
import Head from 'next/head';
import PrimaryBannerSlide from '../components/PrimaryBannerSlide';

import styles from './home.module.scss';

const Home: NextPage = () => (
  <>
    <Head>
      <title>Início | CezarModz</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={`container ${styles.bannerContainer}`}>
      <PrimaryBannerSlide />
    </div>
  </>
);

export default Home;
