import type { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import Button from '../components/Button';
import PrimaryBannerSlide from '../components/PrimaryBannerSlide';

import api from '../services/api';

import styles from './home.module.scss';

type Type = {
  id: number;
  type: string;
};

type HomeProps = {
  types: Type[];
};

export default function Home({ types }: HomeProps) {
  return (
    <>
      <Head>
        <title>Início | CezarModz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`container ${styles.bannerContainer}`}>
        <PrimaryBannerSlide />
      </div>
      <section className="container">
        <main className={`${styles.choseProductBox}`}>
          <h1> Produtos </h1>
          <p> Contas e serviços para PS4 e XBOX </p>
          {types.map((type) => (
            <Link href="/">
              <a>
                <Button text={type.type} />
              </a>
            </Link>
          ))}
        </main>
      </section>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const response = await api.get('/tipos');

  return {
    props: {
      types: response.data,
    },
    revalidate: 60 * 60 * 24,
  };
};
